# Generated by Django 2.2.7 on 2019-11-11 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reference_model", "0001_initial"),
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meter",
            fields=[
                (
                    "meterintervalframe_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reference_model.MeterIntervalFrame",
                    ),
                ),
                ("sa_id", models.IntegerField(db_index=True, unique=True)),
                (
                    "rate_plan_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                (
                    "load_serving_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meters",
                        to="reference_model.LoadServingEntity",
                    ),
                ),
            ],
            options={"ordering": ["id"]},
            bases=("reference_model.meterintervalframe",),
        ),
        migrations.AddField(
            model_name="customerpopulation",
            name="load_serving_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_populations",
                to="reference_model.LoadServingEntity",
            ),
        ),
        migrations.AddField(
            model_name="customercluster",
            name="customer_population",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_clusters",
                to="customer.CustomerPopulation",
            ),
        ),
        migrations.AddField(
            model_name="customercluster",
            name="meters",
            field=models.ManyToManyField(
                related_name="customer_clusters", to="customer.Meter"
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="data_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="channels",
                to="reference_model.DataUnit",
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="meter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channels",
                to="customer.Meter",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customerpopulation",
            unique_together={
                ("name", "frame288_type", "normalize", "load_serving_entity")
            },
        ),
        migrations.AlterUniqueTogether(
            name="channel", unique_together={("export", "meter")}
        ),
    ]
