# Generated by Django 2.2.7 on 2020-02-25 23:50

import beo_datastore.libs.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_auto_repr


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reference_model", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OriginFile",
            fields=[
                (
                    "metergroup_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reference_model.MeterGroup",
                    ),
                ),
                ("file", models.FileField(upload_to="origin_files")),
                (
                    "expected_meter_count",
                    models.IntegerField(blank=True, null=True),
                ),
                ("md5sum", models.CharField(max_length=32)),
                (
                    "load_serving_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="origin_files",
                        to="reference_model.LoadServingEntity",
                    ),
                ),
                (
                    "owners",
                    models.ManyToManyField(
                        blank=True,
                        related_name="origin_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["id"]},
            bases=(
                beo_datastore.libs.models.IntervalFrameFileMixin,
                "reference_model.metergroup",
            ),
        ),
        migrations.CreateModel(
            name="CustomerPopulation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "frame288_type",
                    models.CharField(
                        choices=[
                            ("average_frame288", "average_frame288"),
                            ("maximum_frame288", "maximum_frame288"),
                            ("minimum_frame288", "minimum_frame288"),
                            ("total_frame288", "total_frame288"),
                        ],
                        max_length=16,
                    ),
                ),
                ("normalize", models.BooleanField()),
                (
                    "load_serving_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_populations",
                        to="reference_model.LoadServingEntity",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "unique_together": {
                    (
                        "name",
                        "frame288_type",
                        "normalize",
                        "load_serving_entity",
                    )
                },
            },
            bases=(django_auto_repr.AutoRepr, models.Model),
        ),
        migrations.CreateModel(
            name="CustomerMeter",
            fields=[
                (
                    "meter_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reference_model.Meter",
                    ),
                ),
                ("sa_id", models.BigIntegerField(db_index=True)),
                (
                    "rate_plan_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("multiple_rate_plans", models.BooleanField(default=False)),
                (
                    "import_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "export_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "load_serving_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meters",
                        to="reference_model.LoadServingEntity",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "unique_together": {("import_hash", "export_hash")},
            },
            bases=("reference_model.meter",),
        ),
        migrations.AddField(
            model_name="customercluster",
            name="customer_population",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_clusters",
                to="customer.CustomerPopulation",
            ),
        ),
        migrations.AddField(
            model_name="customercluster",
            name="meters",
            field=models.ManyToManyField(
                related_name="customer_clusters", to="reference_model.Meter"
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="data_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="channels",
                to="reference_model.DataUnit",
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="meter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channels",
                to="customer.CustomerMeter",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="channel", unique_together={("export", "meter")}
        ),
    ]
