# Generated by Django 2.2.7 on 2019-11-14 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reference_model", "0001_initial"),
        ("customer", "0002_auto_20191111_2359"),
    ]

    operations = [
        migrations.RemoveField(model_name="customercluster", name="meters"),
        migrations.AddField(
            model_name="customercluster",
            name="meter_intervalframes",
            field=models.ManyToManyField(
                related_name="customer_clusters",
                to="reference_model.MeterIntervalFrame",
            ),
        ),
        migrations.AlterField(
            model_name="customerpopulation",
            name="load_serving_entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_populations",
                to="reference_model.LoadServingEntity",
            ),
        ),
    ]
