# Generated by Django 2.2.7 on 2020-02-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("customer", "0002_auto_20200210_2057")]

    operations = [
        migrations.AddField(
            model_name="customermeter",
            name="multiple_rate_plans",
            field=models.BooleanField(default=False),
        )
    ]
