# Generated by Django 2.2.7 on 2019-12-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("customer", "0003_auto_20191114_1855")]

    operations = [
        migrations.AlterField(
            model_name="meter",
            name="sa_id",
            field=models.BigIntegerField(db_index=True, unique=True),
        )
    ]
