# Generated by Django 2.2.7 on 2020-02-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("customer", "0003_customermeter_multiple_rate_plans")]

    operations = [
        migrations.AddField(
            model_name="customermeter",
            name="export_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="customermeter",
            name="import_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="originfile",
            name="expected_meter_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="customermeter",
            unique_together={("import_hash", "export_hash")},
        ),
    ]
