# Generated by Django 2.2.7 on 2020-02-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("customer", "0005_auto_20200125_0015")]

    operations = [
        migrations.RenameField(
            model_name="meter",
            old_name="_load_serving_entity",
            new_name="load_serving_entity",
        )
    ]
