# Generated by Django 2.2.7 on 2020-09-17 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_user", "0002_auto_20200812_1906"),
        ("customer", "0006_auto_20200724_1725"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="customermeter",
            unique_together={
                (
                    "sa_id",
                    "rate_plan_name",
                    "multiple_rate_plans",
                    "load_serving_entity",
                    "import_hash",
                    "export_hash",
                )
            },
        )
    ]
