# Generated by Django 2.2.7 on 2020-12-04 17:52

import beo_datastore.libs.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("auth_user", "0002_auto_20200812_1906"),
        ("customer", "0007_auto_20200917_2230"),
    ]

    operations = [
        migrations.CreateModel(
            name="GasUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("usage_hash", models.BigIntegerField(unique=True)),
            ],
            options={
                "ordering": ["id"],
            },
            bases=(
                beo_datastore.libs.models.AutoReprMixin,
                models.Model,
                beo_datastore.libs.models.IntervalFrameFileMixin,
            ),
        ),
        migrations.AddField(
            model_name="customermeter",
            name="gas_usage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="customer.GasUsage",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customermeter",
            unique_together={
                (
                    "sa_id",
                    "rate_plan_name",
                    "multiple_rate_plans",
                    "load_serving_entity",
                    "import_hash",
                    "export_hash",
                    "gas_usage",
                )
            },
        ),
    ]
