# Generated by Django 2.2.7 on 2020-12-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0008_auto_20201204_1752"),
    ]

    operations = [
        migrations.AddField(
            model_name="customermeter",
            name="total_therms",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
