# Generated by Django 2.2.7 on 2020-12-17 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0009_customermeter_total_therms"),
    ]

    operations = [
        migrations.AlterModelOptions(name="customermeter", options={}),
        migrations.AlterModelOptions(
            name="originfile", options={"base_manager_name": "objects"},
        ),
    ]
