# Generated by Django 2.2 on 2019-04-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BuildingType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("floor_area", models.IntegerField()),
                ("number_of_floors", models.IntegerField()),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="DataUnit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=8)),
            ],
            options={"ordering": ["id"]},
        ),
    ]
