# Generated by Django 2.2.2 on 2019-08-13 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reference_model", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="loadservingentity",
            options={
                "ordering": ["id"],
                "verbose_name_plural": "load serving entities",
            },
        )
    ]
