# Generated by Django 2.2.7 on 2020-02-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("reference_model", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="metergroup",
            name="name",
            field=models.CharField(blank=True, max_length=128, null=True),
        )
    ]
