# Generated by Django 2.2.7 on 2020-05-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("reference_model", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="derstrategy",
            name="description",
            field=models.TextField(blank=True, null=True),
        )
    ]
