# Generated by Django 2.2.7 on 2020-03-03 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reference_model", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="derconfiguration", options={"ordering": ["created_at"]}
        ),
        migrations.AlterModelOptions(
            name="dersimulation", options={"ordering": ["-created_at"]}
        ),
        migrations.AlterModelOptions(
            name="derstrategy", options={"ordering": ["-created_at"]}
        ),
        migrations.AlterModelOptions(
            name="meter", options={"ordering": ["-created_at"]}
        ),
        migrations.AlterModelOptions(
            name="metergroup", options={"ordering": ["-created_at"]}
        ),
        migrations.RemoveField(model_name="derconfiguration", name="der_type"),
        migrations.RemoveField(model_name="derstrategy", name="der_type"),
        migrations.DeleteModel(name="DERType"),
    ]
