# Generated by Django 2.2.7 on 2019-12-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("reference_model", "0002_auto_20191205_1724")]

    operations = [
        migrations.AlterModelOptions(
            name="meterintervalframe", options={"ordering": ["id"]}
        ),
        migrations.AddField(
            model_name="originfile",
            name="md5sum",
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
