# Generated by Django 2.2.7 on 2020-05-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_model", "0002_derstrategy_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="derstrategy",
            name="objective",
            field=models.CharField(
                blank=True,
                choices=[
                    ("load_flattening", "Load Flattening"),
                    ("reduce_bill", "Reduce Bill"),
                    ("reduce_ghg", "Reduce GHG"),
                    ("reduce_cca_finance", "Minimize CCA Financial Impacts"),
                ],
                max_length=18,
                null=True,
            ),
        ),
    ]
