# Generated by Django 2.2.7 on 2020-01-25 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("reference_model", "0003_auto_20191210_1905")]

    operations = [
        migrations.AddField(
            model_name="loadservingentity",
            name="_parent_utility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="load_serving_entities",
                to="reference_model.LoadServingEntity",
            ),
        ),
        migrations.AddField(
            model_name="loadservingentity",
            name="short_name",
            field=models.CharField(default="AAA", max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="originfile",
            name="load_serving_entity",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="origin_files",
                to="reference_model.LoadServingEntity",
            ),
            preserve_default=False,
        ),
    ]
