# Generated by Django 2.2.7 on 2020-02-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("reference_model", "0004_auto_20200125_0015")]

    operations = [
        migrations.AlterField(
            model_name="originfile",
            name="file",
            field=models.FileField(upload_to="origin_files"),
        )
    ]
