# Generated by Django 2.2.7 on 2020-08-04 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reference_model", "0004_auto_20200804_0030"),
        ("simulation", "0005_auto_20200804_0054"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dersimulation",
            old_name="post_DER_total_new",
            new_name="post_DER_total",
        ),
        migrations.RenameField(
            model_name="dersimulation",
            old_name="pre_DER_total_new",
            new_name="pre_DER_total",
        ),
    ]
