# Generated by Django 2.2.7 on 2020-09-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_model", "0005_auto_20200804_0054"),
    ]

    operations = [
        migrations.AddField(
            model_name="meter",
            name="max_monthly_demand",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meter",
            name="total_kwh",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metergroup",
            name="max_monthly_demand",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metergroup",
            name="total_kwh",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
