# Generated by Django 2.2.7 on 2020-10-06 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0002_auto_20201006_1852"),
        ("reference_model", "0007_remove_study_polymorphic_ctype"),
    ]

    operations = [
        migrations.DeleteModel(name="Study",),
    ]
