# Generated by Django 2.2.7 on 2020-10-06 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utility_rate", "0003_auto_20201006_2219"),
        ("reference_model", "0008_delete_study"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="voltagecategory",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="voltagecategory",
            name="load_serving_entity",
        ),
        migrations.DeleteModel(
            name="Sector",
        ),
        migrations.DeleteModel(
            name="VoltageCategory",
        ),
    ]
