# Generated by Django 2.2.7 on 2020-10-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("reference_model", "0008_delete_study")]

    operations = [
        migrations.AddField(
            model_name="metergroup",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="metergroup",
            name="completed_incompleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metergroup",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="metergroup",
            name="locked_unlocked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
