# Generated by Django 2.2.7 on 2020-11-05 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth_user", "0002_auto_20200812_1906"),
        ("reference_model", "0010_auto_20201014_2237"),
    ]

    operations = [
        migrations.AddField(
            model_name="derconfiguration",
            name="load_serving_entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="der_configurations",
                to="auth_user.LoadServingEntity",
            ),
        ),
        migrations.AddField(
            model_name="derstrategy",
            name="load_serving_entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="der_strategies",
                to="auth_user.LoadServingEntity",
            ),
        ),
    ]
