# Generated by Django 2.2.7 on 2020-12-21 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reference_model", "0011_auto_20201105_0320"),
    ]

    operations = [
        migrations.AlterField(
            model_name="derconfiguration",
            name="load_serving_entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="der_configurations",
                to="auth_user.LoadServingEntity",
            ),
        ),
        migrations.AlterField(
            model_name="derstrategy",
            name="load_serving_entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="der_strategies",
                to="auth_user.LoadServingEntity",
            ),
        ),
    ]
