version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn beo_datastore.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/api/staticfiles
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/api/staticfiles
    ports:
      - 1337:80
    depends_on:
      - api

volumes:
  static_volume:
