# Generated by Django 2.2.2 on 2019-07-16 16:57

import beo_datastore.libs.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_auto_repr


class Migration(migrations.Migration):

    initial = True

    dependencies = [("customer", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="BatteryConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                ("discharge_duration_hours", models.IntegerField()),
                (
                    "efficiency",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=0
                            ),
                            django.core.validators.MaxValueValidator(
                                limit_value=1
                            ),
                        ]
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "unique_together": {
                    ("rating", "discharge_duration_hours", "efficiency")
                },
            },
            bases=(django_auto_repr.AutoRepr, models.Model),
        ),
        migrations.CreateModel(
            name="BatterySchedule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash", models.CharField(max_length=64, unique=True)),
            ],
            options={"ordering": ["id"]},
            bases=(
                beo_datastore.libs.models.Frame288FileMixin,
                django_auto_repr.AutoRepr,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="DERBatterySimulation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end_limit", models.DateTimeField()),
                (
                    "battery_configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="der_battery_simulations",
                        to="simulation.BatteryConfiguration",
                    ),
                ),
                (
                    "charge_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charge_schedule_der_battery_simulations",
                        to="simulation.BatterySchedule",
                    ),
                ),
                (
                    "discharge_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discharge_schedule_der_battery_simulations",
                        to="simulation.BatterySchedule",
                    ),
                ),
                (
                    "meter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="der_battery_simulations",
                        to="customer.Meter",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "unique_together": {
                    (
                        "meter",
                        "battery_configuration",
                        "charge_schedule",
                        "discharge_schedule",
                        "start",
                        "end_limit",
                    )
                },
            },
            bases=(
                beo_datastore.libs.models.IntervalFrameFileMixin,
                django_auto_repr.AutoRepr,
                models.Model,
            ),
        ),
    ]
