# Generated by Django 2.2.2 on 2019-08-08 20:57

from django.db import migrations, models
import django.db.models.deletion
import django_auto_repr


class Migration(migrations.Migration):

    dependencies = [("simulation", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="BatteryStrategy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=88, null=True),
                ),
                (
                    "charge_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charge_schedule_battery_strategies",
                        to="simulation.BatterySchedule",
                    ),
                ),
                (
                    "discharge_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discharge_schedule_battery_strategies",
                        to="simulation.BatterySchedule",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "battery strategies",
                "ordering": ["id"],
                "unique_together": {("charge_schedule", "discharge_schedule")},
            },
            bases=(django_auto_repr.AutoRepr, models.Model),
        )
    ]
