# Generated by Django 2.2.7 on 2019-11-14 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_auto_20191114_1855"),
        ("simulation", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="storedbatterysimulation",
            old_name="meter",
            new_name="meter_intervalframe",
        ),
        migrations.AlterUniqueTogether(
            name="storedbatterysimulation",
            unique_together={
                (
                    "meter_intervalframe",
                    "battery_configuration",
                    "battery_strategy",
                    "start",
                    "end_limit",
                )
            },
        ),
        migrations.AlterField(
            model_name="storedbatterysimulation",
            name="meter_intervalframe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="battery_simulations",
                to="reference_model.MeterIntervalFrame",
            ),
        ),
    ]
