# Generated by Django 2.2.7 on 2020-07-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("simulation", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="batteryschedule", name="hash")
    ]
