# Generated by Django 2.2.7 on 2020-01-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("simulation", "0002_auto_20191114_2234")]

    operations = [
        migrations.AlterField(
            model_name="batterystrategy",
            name="name",
            field=models.CharField(blank=True, max_length=128, null=True),
        )
    ]
