# Generated by Django 2.2.7 on 2020-07-24 17:25

from django.db import migrations, models

from der.simulation.models import BatterySchedule


def update_hash(apps, schema_editor):
    """
    Update hash values on BatterySchedule handled in clean() method.
    """
    for strategy in BatterySchedule.objects.all():
        strategy.save()


class Migration(migrations.Migration):

    dependencies = [("simulation", "0002_remove_batteryschedule_hash")]

    operations = [
        migrations.AddField(
            model_name="batteryschedule",
            name="hash",
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RunPython(
            update_hash, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="batteryschedule",
            name="hash",
            field=models.BigIntegerField(unique=True),
        ),
    ]
