# Generated by Django 2.2.2 on 2019-11-06 00:34

from django.core.exceptions import ValidationError
from django.db import migrations, models
import django.db.models.deletion

from der.simulation.models import BatteryStrategy, StoredBatterySimulation


def create_battery_strategies(apps, schema_editor):
    """
    Turn charge_schedule and discharge_schedule into BatteryStrategy.
    """
    for sim in StoredBatterySimulation.objects.all():
        battery_strategy, _ = BatteryStrategy.objects.get_or_create(
            charge_schedule=sim._charge_schedule,
            discharge_schedule=sim._discharge_schedule,
        )
        battery_strategy.name = "Auto-created by Django migration."
        battery_strategy.save()

        try:
            sim.battery_strategy = battery_strategy
            sim.save()
        except ValidationError:
            sim.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_customercluster_customerpopulation"),
        ("simulation", "0002_batterystrategy"),
    ]

    operations = [
        migrations.RenameField(
            model_name="storedbatterysimulation",
            old_name="charge_schedule",
            new_name="_charge_schedule",
        ),
        migrations.RenameField(
            model_name="storedbatterysimulation",
            old_name="discharge_schedule",
            new_name="_discharge_schedule",
        ),
        migrations.AddField(
            model_name="storedbatterysimulation",
            name="battery_strategy",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="battery_strategies",
                to="simulation.BatteryStrategy",
            ),
            preserve_default=False,
        ),
        # migrations.RunPython(create_battery_strategies),
        migrations.AlterUniqueTogether(
            name="storedbatterysimulation",
            unique_together={
                (
                    "meter",
                    "battery_configuration",
                    "battery_strategy",
                    "start",
                    "end_limit",
                )
            },
        ),
    ]
