# Generated by Django 2.2.2 on 2019-11-06 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("simulation", "0003_auto_20191106_0034")]

    operations = [
        migrations.RemoveField(
            model_name="storedbatterysimulation", name="_charge_schedule"
        ),
        migrations.RemoveField(
            model_name="storedbatterysimulation", name="_discharge_schedule"
        ),
    ]
