# Generated by Django 2.2.7 on 2020-08-04 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reference_model", "0004_auto_20200804_0030"),
        ("simulation", "0004_evseconfiguration_evsestrategy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storedbatterysimulation", name="post_DER_total",
        ),
        migrations.RemoveField(
            model_name="storedbatterysimulation", name="pre_DER_total",
        ),
    ]
