# Generated by Django 2.2.7 on 2019-11-07 00:19

from django.db import migrations, models

from der.simulation.models import StoredBatterySimulation


def update_usage_totals(apps, schema_editor):
    """
    Update StoredBatterySimulation pre-DER and post-DER usage totals.
    """
    for battery_simulation in StoredBatterySimulation.objects.all():
        pre_total_frame288 = (
            battery_simulation.pre_intervalframe.total_frame288
        )
        battery_simulation.pre_DER_total = (
            pre_total_frame288.dataframe.sum().sum()
        )
        post_total_frame288 = (
            battery_simulation.post_intervalframe.total_frame288
        )
        battery_simulation.post_DER_total = (
            post_total_frame288.dataframe.sum().sum()
        )
        battery_simulation.save()


class Migration(migrations.Migration):

    dependencies = [("simulation", "0004_auto_20191106_0041")]

    operations = [
        migrations.AddField(
            model_name="storedbatterysimulation",
            name="post_DER_total",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="storedbatterysimulation",
            name="pre_DER_total",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.RunPython(
            update_usage_totals, reverse_code=migrations.RunPython.noop
        ),
    ]
