# Generated by Django 2.2.7 on 2020-08-20 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("simulation", "0006_evsesimulation")]

    operations = [
        migrations.AlterModelOptions(
            name="evsesimulation",
            options={
                "base_manager_name": "objects",
                "verbose_name_plural": "EVSE simulations",
            },
        )
    ]
