# Generated by Django 2.2.7 on 2020-08-21 21:21

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("reference_model", "0005_auto_20200804_0054"),
        ("simulation", "0007_auto_20200820_2015"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolarPVConfiguration",
            fields=[
                (
                    "derconfiguration_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reference_model.DERConfiguration",
                    ),
                ),
                ("parameters", jsonfield.fields.JSONField(unique=True)),
                ("stored_response", jsonfield.fields.JSONField()),
            ],
            options={
                "verbose_name_plural": "Solar PV configurations",
                "ordering": ["id"],
            },
            bases=("reference_model.derconfiguration",),
        ),
        migrations.CreateModel(
            name="SolarPVStrategy",
            fields=[
                (
                    "derstrategy_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reference_model.DERStrategy",
                    ),
                ),
                ("parameters", jsonfield.fields.JSONField(unique=True)),
            ],
            options={
                "verbose_name_plural": "Solar PV strategies",
                "ordering": ["id"],
            },
            bases=("reference_model.derstrategy",),
        ),
    ]
