# Generated by Django 2.2.7 on 2020-09-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("simulation", "0009_solarpvsimulation")]

    operations = [
        migrations.AlterField(
            model_name="batteryconfiguration",
            name="rating",
            field=models.FloatField(),
        )
    ]
