# Generated by Django 2.2.7 on 2020-12-04 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0011_auto_20201105_0320"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evseconfiguration", name="ev_mpg_eq",
        ),
        migrations.AddField(
            model_name="evseconfiguration",
            name="evse_utilization",
            field=models.FloatField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(limit_value=0),
                    django.core.validators.MaxValueValidator(limit_value=1),
                ],
            ),
        ),
        # Drop default
        migrations.AlterField(
            model_name="evseconfiguration",
            name="evse_utilization",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(limit_value=0),
                    django.core.validators.MaxValueValidator(limit_value=1),
                ]
            ),
        ),
    ]
