# Generated by Django 2.2.7 on 2020-12-09 02:56

from django.db import migrations


def drop_evse_configuration_duplicates(apps, schema_editor):
    """
    Drops any EVSEConfiguration duplicates now that the `ev_efficiency` and
    `ev_capacity` columns have been dropped. This is done so that future calls
    to `get_or_create` don't fail because there's more than 1 configuration with
    the same params. EVSEConfiguration models must be in the same LSE to be
    considered duplicates. When deleting duplicates, the oldest duplicate
    will be kept with the assumption that it is used in more scenarios.
    """
    EVSEConfiguration = apps.get_model("simulation.EVSEConfiguration")
    configurations = EVSEConfiguration.objects.order_by("-created_at").all()
    for configuration in configurations:
        # If there is already a configuration object with the remaining
        # parameters (within the same LSE), drop this one. This is so that
        # future calls to `get_or_create` don't fail because there's more than 1
        # configuration with the same params
        other_exists = (
            EVSEConfiguration.objects.exclude(id=configuration.id)
            .filter(
                ev_mpkwh=configuration.ev_mpkwh,
                evse_rating=configuration.evse_rating,
                ev_count=configuration.ev_count,
                evse_count=configuration.evse_count,
                evse_utilization=configuration.evse_utilization,
                load_serving_entity=configuration.load_serving_entity,
            )
            .exists()
        )

        if other_exists:
            configuration.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0014_auto_20201209_0135"),
    ]

    operations = []
