# Generated by Django 2.2.7 on 2020-12-15 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0016_auto_20201211_1457"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fuelswitchingconfiguration",
            name="performance_coefficient",
        ),
    ]
