version: 2
jobs:
  build:
    working_directory: ~/beo_datastore
    docker:
      - image: circleci/python:3.6.9
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:10.0
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    environment:
      APP_ENV: local
      SECRET_KEY: CIRCLETEST
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: beo_datastore
      SQL_USER: root
      SQL_PASSWORD: circle_test
      SQL_HOST: localhost
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: deps10-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - save_cache:
          key: deps10-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - '.venv'
            - '/usr/local/bin'
            - '/usr/local/lib/python3.6/site-packages'
      - run:
          command: |
            pipenv run python manage.py test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
