# Generated by Django 2.2 on 2019-04-05 22:50

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("reference_unit", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="ServiceDrop",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sa_id", models.IntegerField(db_index=True)),
                (
                    "rate_plan",
                    models.CharField(
                        blank=True, db_index=True, max_length=16, null=True
                    ),
                ),
                ("state", localflavor.us.models.USStateField(max_length=2)),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="Meter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("export", models.BooleanField(default=False)),
                (
                    "data_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meters",
                        to="reference_unit.DataUnit",
                    ),
                ),
                (
                    "service_drop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meters",
                        to="interval.ServiceDrop",
                    ),
                ),
            ],
            options={"ordering": ["id"]},
        ),
    ]
