# Generated by Django 2.2.7 on 2020-03-19 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("utility_rate", "0001_initial"),
        ("auth_user", "0001_initial"),
        ("reference_model", "0001_initial"),
        ("ghg", "0002_auto_20200319_1747"),
        ("procurement", "0002_auto_20200319_1747"),
    ]

    operations = [
        migrations.CreateModel(
            name="SingleScenarioStudy",
            fields=[
                (
                    "study_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reference_model.Study",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end_limit", models.DateTimeField()),
                (
                    "der_configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="single_scenario_studies",
                        to="reference_model.DERConfiguration",
                    ),
                ),
                (
                    "der_strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="single_scenario_studies",
                        to="reference_model.DERStrategy",
                    ),
                ),
                (
                    "ghg_rates",
                    models.ManyToManyField(
                        blank=True,
                        related_name="single_scenario_studies",
                        to="ghg.GHGRate",
                    ),
                ),
                (
                    "load_serving_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="single_scenario_studies",
                        to="auth_user.LoadServingEntity",
                    ),
                ),
                (
                    "meter_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="single_scenario_studies",
                        to="reference_model.MeterGroup",
                    ),
                ),
                (
                    "meters",
                    models.ManyToManyField(
                        blank=True,
                        related_name="single_scenario_studies",
                        to="reference_model.Meter",
                    ),
                ),
                (
                    "rate_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="single_scenario_studies",
                        to="utility_rate.RatePlan",
                    ),
                ),
                (
                    "system_profiles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="single_scenario_studies",
                        to="procurement.SystemProfile",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "unique_together": {
                    (
                        "start",
                        "end_limit",
                        "der_strategy",
                        "der_configuration",
                        "meter_group",
                        "load_serving_entity",
                        "rate_plan",
                    )
                },
            },
            bases=("reference_model.study",),
        ),
        migrations.CreateModel(
            name="MultipleScenarioStudy",
            fields=[
                (
                    "study_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reference_model.Study",
                    ),
                ),
                (
                    "single_scenario_studies",
                    models.ManyToManyField(
                        related_name="multiple_scenario_studies",
                        to="study.SingleScenarioStudy",
                    ),
                ),
            ],
            options={"ordering": ["id"]},
            bases=("reference_model.study",),
        ),
    ]
