# Generated by Django 2.2.7 on 2020-03-27 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="singlescenariostudy", unique_together=set(),
        ),
    ]
