# Generated by Django 2.2.7 on 2020-10-06 18:52

import beo_datastore.libs.models
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("ghg", "0002_auto_20200319_1747"),
        ("utility_rate", "0002_auto_20200330_2207"),
        ("reference_model", "0007_remove_study_polymorphic_ctype"),
        ("auth_user", "0002_auto_20200812_1906"),
        ("procurement", "0005_auto_20200626_2057"),
        ("study", "0001_squashed_0007_auto_20200922_0058"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "metergroup_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reference_model.MeterGroup",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end_limit", models.DateTimeField()),
                (
                    "_report",
                    jsonfield.fields.JSONField(
                        blank=True, default={}, null=True
                    ),
                ),
                (
                    "_report_summary",
                    jsonfield.fields.JSONField(
                        blank=True, default={}, null=True
                    ),
                ),
                (
                    "caiso_rates",
                    models.ManyToManyField(
                        blank=True,
                        related_name="scenarios",
                        to="procurement.CAISORate",
                    ),
                ),
                (
                    "der_configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenarios",
                        to="reference_model.DERConfiguration",
                    ),
                ),
                (
                    "der_strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenarios",
                        to="reference_model.DERStrategy",
                    ),
                ),
                (
                    "ghg_rates",
                    models.ManyToManyField(
                        blank=True, related_name="scenarios", to="ghg.GHGRate"
                    ),
                ),
                (
                    "load_serving_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenarios",
                        to="auth_user.LoadServingEntity",
                    ),
                ),
                (
                    "meter_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenarios",
                        to="reference_model.MeterGroup",
                    ),
                ),
                (
                    "meters",
                    models.ManyToManyField(
                        blank=True,
                        related_name="scenarios",
                        to="reference_model.Meter",
                    ),
                ),
                (
                    "rate_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenarios",
                        to="utility_rate.RatePlan",
                    ),
                ),
                (
                    "system_profiles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="scenarios",
                        to="procurement.SystemProfile",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
            bases=(
                beo_datastore.libs.models.IntervalFrameFileMixin,
                "reference_model.metergroup",
            ),
        ),
        migrations.RemoveField(
            model_name="singlescenariostudy", name="caiso_rates",
        ),
        migrations.RemoveField(
            model_name="singlescenariostudy", name="der_configuration",
        ),
        migrations.RemoveField(
            model_name="singlescenariostudy", name="der_strategy",
        ),
        migrations.RemoveField(
            model_name="singlescenariostudy", name="ghg_rates",
        ),
        migrations.RemoveField(
            model_name="singlescenariostudy", name="load_serving_entity",
        ),
        migrations.RemoveField(
            model_name="singlescenariostudy", name="meter_group",
        ),
        migrations.RemoveField(
            model_name="singlescenariostudy", name="meters",
        ),
        migrations.RemoveField(
            model_name="singlescenariostudy", name="rate_plan",
        ),
        migrations.RemoveField(
            model_name="singlescenariostudy", name="study_ptr",
        ),
        migrations.RemoveField(
            model_name="singlescenariostudy", name="system_profiles",
        ),
        migrations.DeleteModel(name="MultipleScenarioStudy",),
        migrations.DeleteModel(name="SingleScenarioStudy",),
    ]
