# Generated by Django 2.2.7 on 2020-10-06 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0002_auto_20201006_1852"),
    ]

    operations = [
        migrations.RemoveField(model_name="scenario", name="meters",),
    ]
