# Generated by Django 2.2.7 on 2020-06-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0004_caisorate_storedprocurementcostcalculation"),
        ("study", "0003_auto_20200506_1823"),
    ]

    operations = [
        migrations.AddField(
            model_name="singlescenariostudy",
            name="caiso_rates",
            field=models.ManyToManyField(
                blank=True,
                related_name="single_scenario_studies",
                to="procurement.CAISORate",
            ),
        )
    ]
