# Generated by Django 2.2.7 on 2020-06-26 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("study", "0004_singlescenariostudy_caiso_rates")]

    operations = [
        migrations.RemoveField(
            model_name="singlescenariostudy", name="_report"
        ),
        migrations.RemoveField(
            model_name="singlescenariostudy", name="_report_summary"
        ),
        migrations.DeleteModel(name="Report"),
        migrations.DeleteModel(name="ReportSummary"),
    ]
