# Generated by Django 2.2.7 on 2020-06-26 22:11

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [("study", "0005_auto_20200626_2057")]

    operations = [
        migrations.AddField(
            model_name="singlescenariostudy",
            name="_report",
            field=jsonfield.fields.JSONField(
                blank=True, default={}, null=True
            ),
        ),
        migrations.AddField(
            model_name="singlescenariostudy",
            name="_report_summary",
            field=jsonfield.fields.JSONField(
                blank=True, default={}, null=True
            ),
        ),
    ]
