# Generated by Django 2.2.7 on 2020-09-22 00:58

from django.db import migrations
from cost.study.models import SingleScenarioStudy


def regenerate_reports(apps, schema_editor):
    """
    Regenerates the reports for all existing scenarios. This data migration
    should be squashed (and thereby deleted) when all environments have been
    deployed to.
    """
    num_scenarios = SingleScenarioStudy.objects.count()
    for index, scenario in enumerate(SingleScenarioStudy.objects.all()):
        print(
            f"Generating reports for scenario (#{index + 1}/{num_scenarios}) "
            f'(name: "{scenario.name}", id: "{scenario.id}")...'
        )
        scenario.generate_reports()


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0006_auto_20200626_2211"),
    ]

    operations = [
        migrations.RunPython(
            regenerate_reports,
            elidable=True,
            reverse_code=migrations.RunPython.noop,
        )
    ]
