# Generated by Django 2.2.7 on 2020-12-21 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0006_scenario_stacked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenario",
            name="der_configuration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scenarios",
                to="reference_model.DERConfiguration",
            ),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="der_strategy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scenarios",
                to="reference_model.DERStrategy",
            ),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="meter_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scenarios",
                to="reference_model.MeterGroup",
            ),
        ),
    ]
