# Generated by Django 2.2 on 2019-04-05 22:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("reference_unit", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="ReferenceBuilding",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=64)),
                (
                    "state",
                    localflavor.us.models.USStateField(
                        blank=True, max_length=2
                    ),
                ),
                (
                    "TMY3_id",
                    models.IntegerField(
                        db_index=True,
                        validators=[
                            django.core.validators.MinValueValidator(100000),
                            django.core.validators.MaxValueValidator(999999),
                        ],
                    ),
                ),
                ("source_file_url", models.URLField(max_length=254)),
                (
                    "building_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reference_buildings",
                        to="reference_unit.BuildingType",
                    ),
                ),
                (
                    "data_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reference_buildings",
                        to="reference_unit.DataUnit",
                    ),
                ),
            ],
            options={"ordering": ["id"]},
        )
    ]
