# Generated by Django 2.2.7 on 2019-11-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reference_model", "0001_initial"),
        ("openei", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="referencebuilding",
            unique_together={
                (
                    "location",
                    "state",
                    "TMY3_id",
                    "source_file_url",
                    "building_type",
                    "data_unit",
                )
            },
        )
    ]
