# Generated by Django 2.2.7 on 2020-02-10 20:57

import beo_datastore.libs.models
from django.db import migrations, models
import django_auto_repr


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoredResourceAdequacyCalculation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pre_DER_total", models.FloatField()),
                ("post_DER_total", models.FloatField()),
            ],
            options={"ordering": ["id"]},
            bases=(django_auto_repr.AutoRepr, models.Model),
        ),
        migrations.CreateModel(
            name="SystemProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
            options={"ordering": ["id"]},
            bases=(
                beo_datastore.libs.models.IntervalFrameFileMixin,
                django_auto_repr.AutoRepr,
                models.Model,
            ),
        ),
    ]
