# Generated by Django 2.2.2 on 2019-08-19 20:39

from django.db import migrations, models
import django.db.models.deletion
import django_auto_repr


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0002_batterystrategy"),
        ("procurement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoredResourceAdequacyCalculation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pre_DER_total", models.FloatField()),
                ("post_DER_total", models.FloatField()),
                (
                    "battery_simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stored_resource_adequacy_calculations",
                        to="simulation.StoredBatterySimulation",
                    ),
                ),
                (
                    "system_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stored_resource_adequacy_calculations",
                        to="procurement.SystemProfile",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "unique_together": {("battery_simulation", "system_profile")},
            },
            bases=(django_auto_repr.AutoRepr, models.Model),
        )
    ]
