# Generated by Django 2.2.7 on 2020-03-19 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reference_model", "0001_initial"),
        ("procurement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storedresourceadequacycalculation",
            name="der_simulation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stored_resource_adequacy_calculations",
                to="reference_model.DERSimulation",
            ),
        ),
        migrations.AddField(
            model_name="storedresourceadequacycalculation",
            name="system_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stored_resource_adequacy_calculations",
                to="procurement.SystemProfile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="systemprofile",
            unique_together={("name", "load_serving_entity")},
        ),
        migrations.AlterUniqueTogether(
            name="storedresourceadequacycalculation",
            unique_together={("der_simulation", "system_profile")},
        ),
    ]
