# Generated by Django 2.2.7 on 2020-06-12 18:55

import beo_datastore.libs.models
from django.db import migrations, models
import django_auto_repr
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [("procurement", "0002_auto_20200319_1747")]

    operations = [
        migrations.CreateModel(
            name="CAISOReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("report_name", models.CharField(max_length=32)),
                ("query_params", jsonfield.fields.JSONField()),
                ("year", models.IntegerField()),
            ],
            options={
                "ordering": ["id"],
                "unique_together": {("report_name", "query_params", "year")},
            },
            bases=(
                beo_datastore.libs.models.IntervalFrameFileMixin,
                django_auto_repr.AutoRepr,
                models.Model,
            ),
        )
    ]
