# Generated by Django 2.2.7 on 2020-06-26 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0004_caisorate_storedprocurementcostcalculation")
    ]

    operations = [
        migrations.AlterField(
            model_name="storedprocurementcostcalculation",
            name="caiso_rate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stored_procurement_calculations",
                to="procurement.CAISORate",
            ),
        ),
        migrations.AlterField(
            model_name="storedprocurementcostcalculation",
            name="der_simulation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stored_procurement_calculations",
                to="reference_model.DERSimulation",
            ),
        ),
    ]
