# Generated by Django 2.2.7 on 2020-10-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("procurement", "0005_auto_20200626_2057")]

    operations = [
        migrations.AddField(
            model_name="storedprocurementcostcalculation",
            name="stacked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="storedresourceadequacycalculation",
            name="stacked",
            field=models.BooleanField(default=False),
        ),
    ]
