# Generated by Django 2.2.7 on 2020-10-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_model", "0010_auto_20201014_2237"),
        ("procurement", "0006_auto_20201019_1700"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storedprocurementcostcalculation",
            name="stacked",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="storedresourceadequacycalculation",
            name="stacked",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name="storedprocurementcostcalculation",
            unique_together={("der_simulation", "caiso_rate", "stacked")},
        ),
        migrations.AlterUniqueTogether(
            name="storedresourceadequacycalculation",
            unique_together={("der_simulation", "system_profile", "stacked")},
        ),
    ]
