# Generated by Django 2.2.7 on 2020-11-12 17:31

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0009_make_ra_rate_value_required"),
    ]

    # Populate one-off datetime values for instances prior to adding timestamp fields.
    operations = [
        migrations.AddField(
            model_name="systemprofile",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 11, 1, 0, 0)
            ),
        ),
        migrations.AddField(
            model_name="systemprofile",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 11, 1, 0, 0)
            ),
        ),
    ]

    # Enforce desire created_at and update_at auto generated datetime values moving forward.
    operations += [
        migrations.AlterField(
            model_name="systemprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="systemprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="systemprofile",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelOptions(
            name="systemprofile",
            options={"ordering": ["-updated_at"]},
        ),
    ]
