# Generated by Django 2.2.7 on 2020-11-14 03:49

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0010_add_timestamp_mixin"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemprofile",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
