# Generated by Django 2.2.7 on 2020-11-14 03:50

import uuid

from django.db import migrations


def gen_uuid(apps, _):
    Model = apps.get_model("procurement", "SystemProfile")
    for row in Model.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0011_add_uuid_field"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
