# Generated by Django 2.2.7 on 2020-11-14 03:51

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0012_populate_uuid_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemprofile",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
