# Generated by Django 2.2.7 on 2020-11-17 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0013_remove_uuid_null"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemprofile",
            name="uuid",
        ),
    ]
