# Generated by Django 2.2.7 on 2020-11-20 16:06

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import beo_datastore.libs.models
import cost.mixins


class Migration(migrations.Migration):

    dependencies = [
        ("auth_user", "0002_auto_20200812_1906"),
        ("procurement", "0014_remove_systemprofile_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcurementRate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2050),
                        ]
                    ),
                ),
                (
                    "load_serving_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procurement_rates",
                        to="auth_user.LoadServingEntity",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("name", "load_serving_entity", "year")},
            },
            bases=(
                beo_datastore.libs.models.IntervalFrameFileMixin,
                cost.mixins.RateDataMixin,
                beo_datastore.libs.models.AutoReprMixin,
                models.Model,
            ),
        ),
    ]
