# Generated by Django 2.2.7 on 2020-12-11 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0015_alter_caisorate"),
    ]

    operations = [
        migrations.RemoveField(model_name="caisorate", name="year"),
    ]
