# Generated by Django 2.2.7 on 2020-12-10 22:47

from django.db import migrations
from cost.procurement.models import CAISORate


def update_caiso_rate_intervalframe(_, __):
    """
    Updates the intervalframe on the CAISORate model using that of its
    CAISOReport. This should have been included in migration 0015 when the
    relationship between CAISORates, CAISOReports and intervalframes changed,
    but the second best time is now.
    """
    for caiso_rate in CAISORate.objects.all():
        # If there's no CAISOReport then this procurement rate is user-uploaded
        report = caiso_rate.caiso_report
        if not report:
            continue

        caiso_rate.intervalframe = report.get_procurement_rate_intervalframe(
            filters=caiso_rate.filters
        )
        caiso_rate.save()


class Migration(migrations.Migration):
    """
    This is a data migration to update the CAISORate intervalframe fields
    """

    dependencies = [
        ("procurement", "0016_remove_caisorate_year"),
    ]

    operations = [
        migrations.RunPython(
            update_caiso_rate_intervalframe,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
    ]
