# Generated by Django 2.2.7 on 2020-12-21 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0017_add_caiso_rate_intervalframes_from_reports"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caisorate",
            name="load_serving_entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth_user.LoadServingEntity",
            ),
        ),
        migrations.AlterField(
            model_name="systemprofile",
            name="load_serving_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="system_profiles",
                to="auth_user.LoadServingEntity",
            ),
        ),
    ]
