# Generated by Django 2.2.7 on 2020-02-25 23:50

from django.db import migrations, models
import django_auto_repr


class Migration(migrations.Migration):

    initial = True

    dependencies = [("customer", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="MultiScenarioOptimization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
            ],
            options={"ordering": ["id"]},
            bases=(django_auto_repr.AutoRepr, models.Model),
        ),
        migrations.CreateModel(
            name="SimulationOptimization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("start", models.DateTimeField()),
                ("end_limit", models.DateTimeField()),
                (
                    "customer_clusters",
                    models.ManyToManyField(
                        blank=True,
                        related_name="simulation_optimizations",
                        to="customer.CustomerCluster",
                    ),
                ),
            ],
            options={"ordering": ["id"]},
            bases=(django_auto_repr.AutoRepr, models.Model),
        ),
    ]
