# Generated by Django 2.2.2 on 2019-07-24 20:25

from django.db import migrations, models
import django.db.models.deletion
import django_auto_repr


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("utility_rate", "0002_auto_20190724_1756"),
        ("simulation", "0001_initial"),
        ("ghg", "0001_initial"),
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatterySimulationOptimization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end_limit", models.DateTimeField()),
                (
                    "battery_configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battery_simulation_optimizations",
                        to="simulation.BatteryConfiguration",
                    ),
                ),
                (
                    "charge_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charge_schedule_battery_simulation_optimizations",
                        to="simulation.BatterySchedule",
                    ),
                ),
                (
                    "discharge_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discharge_schedule_battery_simulation_optimizations",
                        to="simulation.BatterySchedule",
                    ),
                ),
                ("ghg_rates", models.ManyToManyField(to="ghg.GHGRate")),
                ("meters", models.ManyToManyField(to="customer.Meter")),
                (
                    "rate_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battery_simulation_optimizations",
                        to="utility_rate.RatePlan",
                    ),
                ),
            ],
            options={"abstract": False},
            bases=(django_auto_repr.AutoRepr, models.Model),
        )
    ]
