# Generated by Django 2.2.2 on 2019-07-30 16:04

from django.db import migrations, models
import django.db.models.deletion
import django_auto_repr


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ghg", "0001_initial"),
        ("customer", "0001_initial"),
        ("simulation", "0001_initial"),
        ("utility_rate", "0002_auto_20190724_1756"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulationOptimization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end_limit", models.DateTimeField()),
                (
                    "battery_configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battery_simulation_optimizations",
                        to="simulation.BatteryConfiguration",
                    ),
                ),
                (
                    "charge_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charge_schedule_battery_simulation_optimizations",
                        to="simulation.BatterySchedule",
                    ),
                ),
                (
                    "discharge_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discharge_schedule_battery_simulation_optimizations",
                        to="simulation.BatterySchedule",
                    ),
                ),
                ("ghg_rates", models.ManyToManyField(to="ghg.GHGRate")),
                ("meters", models.ManyToManyField(to="customer.Meter")),
                (
                    "rate_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battery_simulation_optimizations",
                        to="utility_rate.RatePlan",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "unique_together": {
                    (
                        "start",
                        "end_limit",
                        "charge_schedule",
                        "discharge_schedule",
                        "battery_configuration",
                        "rate_plan",
                    )
                },
            },
            bases=(django_auto_repr.AutoRepr, models.Model),
        ),
        migrations.CreateModel(
            name="MultiScenarioOptimization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "simulation_optimizations",
                    models.ManyToManyField(
                        to="optimization.SimulationOptimization"
                    ),
                ),
            ],
            options={"ordering": ["id"]},
            bases=(django_auto_repr.AutoRepr, models.Model),
        ),
    ]
