# Generated by Django 2.2.7 on 2020-02-25 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("optimization", "0001_initial"),
        ("utility_rate", "0001_initial"),
        ("ghg", "0002_auto_20200225_2350"),
        ("procurement", "0001_initial"),
        ("reference_model", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulationoptimization",
            name="der_configuration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="simulation_optimizations",
                to="reference_model.DERConfiguration",
            ),
        ),
        migrations.AddField(
            model_name="simulationoptimization",
            name="der_strategy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="simulation_optimizations",
                to="reference_model.DERStrategy",
            ),
        ),
        migrations.AddField(
            model_name="simulationoptimization",
            name="ghg_rates",
            field=models.ManyToManyField(
                blank=True,
                related_name="simulation_optimizations",
                to="ghg.GHGRate",
            ),
        ),
        migrations.AddField(
            model_name="simulationoptimization",
            name="load_serving_entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="simulation_optimizations",
                to="reference_model.LoadServingEntity",
            ),
        ),
        migrations.AddField(
            model_name="simulationoptimization",
            name="meters",
            field=models.ManyToManyField(
                blank=True,
                related_name="simulation_optimizations",
                to="reference_model.Meter",
            ),
        ),
        migrations.AddField(
            model_name="simulationoptimization",
            name="rate_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="simulation_optimizations",
                to="utility_rate.RatePlan",
            ),
        ),
        migrations.AddField(
            model_name="simulationoptimization",
            name="system_profiles",
            field=models.ManyToManyField(
                blank=True,
                related_name="simulation_optimizations",
                to="procurement.SystemProfile",
            ),
        ),
        migrations.AddField(
            model_name="multiscenariooptimization",
            name="simulation_optimizations",
            field=models.ManyToManyField(
                related_name="multi_scenario_optimizations",
                to="optimization.SimulationOptimization",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="simulationoptimization",
            unique_together={
                (
                    "name",
                    "start",
                    "end_limit",
                    "der_strategy",
                    "der_configuration",
                    "load_serving_entity",
                    "rate_plan",
                )
            },
        ),
    ]
