# Generated by Django 2.2.2 on 2019-08-08 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("optimization", "0002_auto_20190808_2057")]

    operations = [
        migrations.RemoveField(
            model_name="simulationoptimization", name="_charge_schedule"
        ),
        migrations.RemoveField(
            model_name="simulationoptimization", name="_discharge_schedule"
        ),
        migrations.AlterField(
            model_name="simulationoptimization",
            name="battery_strategy",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="simulation_optimizations",
                to="simulation.BatteryStrategy",
            ),
            preserve_default=False,
        ),
    ]
