# Generated by Django 2.2.2 on 2019-08-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_customercluster_customerpopulation"),
        ("optimization", "0003_auto_20190808_2244"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulationoptimization",
            name="customer_clusters",
            field=models.ManyToManyField(
                blank=True,
                related_name="simulation_optimizations",
                to="customer.CustomerCluster",
            ),
        ),
        migrations.AlterField(
            model_name="multiscenariooptimization",
            name="simulation_optimizations",
            field=models.ManyToManyField(
                related_name="multi_scenario_optimizations",
                to="optimization.SimulationOptimization",
            ),
        ),
        migrations.AlterField(
            model_name="simulationoptimization",
            name="ghg_rates",
            field=models.ManyToManyField(
                blank=True,
                related_name="simulation_optimizations",
                to="ghg.GHGRate",
            ),
        ),
        migrations.AlterField(
            model_name="simulationoptimization",
            name="meters",
            field=models.ManyToManyField(
                blank=True,
                related_name="simulation_optimizations",
                to="customer.Meter",
            ),
        ),
    ]
