# Generated by Django 2.2.2 on 2019-08-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0002_batterystrategy"),
        ("utility_rate", "0001_initial"),
        ("reference_model", "0002_auto_20190813_2242"),
        ("optimization", "0004_auto_20190812_1709"),
    ]

    operations = [
        migrations.AddField(
            model_name="multiscenariooptimization",
            name="name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="simulationoptimization",
            name="name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="simulationoptimization",
            unique_together={
                (
                    "name",
                    "start",
                    "end_limit",
                    "battery_strategy",
                    "battery_configuration",
                    "load_serving_entity",
                    "rate_plan",
                )
            },
        ),
    ]
