# Generated by Django 2.2.2 on 2019-08-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0002_storedresourceadequacycalculation"),
        ("optimization", "0005_auto_20190815_2211"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulationoptimization",
            name="system_profiles",
            field=models.ManyToManyField(
                blank=True,
                related_name="simulation_optimizations",
                to="procurement.SystemProfile",
            ),
        )
    ]
