# Generated by Django 2.2.7 on 2020-12-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_user", "0002_auto_20200812_1906"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loadservingentity",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
