# Generated by Django 2.2.7 on 2020-12-17 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_user", "0003_auto_20201204_0213"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loadservingentity",
            options={
                "ordering": ["name"],
                "verbose_name_plural": "load serving entities",
            },
        ),
    ]
