# Generated by Django 2.2 on 2019-05-13 18:30

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [("reference_model", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="RatePlan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
                ("demand_min", models.IntegerField(blank=True, null=True)),
                ("demand_max", models.IntegerField(blank=True, null=True)),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rate_plans",
                        to="reference_model.Sector",
                    ),
                ),
                (
                    "utility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rate_plans",
                        to="reference_model.Utility",
                    ),
                ),
                (
                    "voltage_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rate_plans",
                        to="reference_model.VoltageCategory",
                    ),
                ),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="RateCollection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate_data", jsonfield.fields.JSONField()),
                (
                    "openei_url",
                    models.URLField(blank=True, max_length=128, null=True),
                ),
                ("utility_url", models.URLField(max_length=128)),
                ("effective_date", models.DateField()),
                (
                    "rate_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_collections",
                        to="utility_rate.RatePlan",
                    ),
                ),
            ],
            options={"ordering": ["effective_date"]},
        ),
    ]
