# Generated by Django 2.2.2 on 2019-07-30 21:53

from django.db import migrations, models
import django.db.models.deletion
import django_auto_repr
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("simulation", "0001_initial"),
        ("reference_model", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RatePlan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
                ("demand_min", models.IntegerField(blank=True, null=True)),
                ("demand_max", models.IntegerField(blank=True, null=True)),
                (
                    "load_serving_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rate_plans",
                        to="reference_model.LoadServingEntity",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rate_plans",
                        to="reference_model.Sector",
                    ),
                ),
                (
                    "voltage_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rate_plans",
                        to="reference_model.VoltageCategory",
                    ),
                ),
            ],
            options={"ordering": ["id"]},
            bases=(django_auto_repr.AutoRepr, models.Model),
        ),
        migrations.CreateModel(
            name="StoredBillCalculation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "battery_simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stored_bill_calculations",
                        to="simulation.StoredBatterySimulation",
                    ),
                ),
                (
                    "rate_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stored_bill_calculations",
                        to="utility_rate.RatePlan",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "unique_together": {("battery_simulation", "rate_plan")},
            },
            bases=(django_auto_repr.AutoRepr, models.Model),
        ),
        migrations.CreateModel(
            name="RateCollection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate_data", jsonfield.fields.JSONField()),
                (
                    "openei_url",
                    models.URLField(blank=True, max_length=128, null=True),
                ),
                ("utility_url", models.URLField(max_length=128)),
                ("effective_date", models.DateField()),
                (
                    "rate_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_collections",
                        to="utility_rate.RatePlan",
                    ),
                ),
            ],
            options={"ordering": ["effective_date"]},
            bases=(django_auto_repr.AutoRepr, models.Model),
        ),
        migrations.CreateModel(
            name="BillComparison",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end_limit", models.DateTimeField()),
                ("pre_DER_total", models.FloatField()),
                ("post_DER_total", models.FloatField()),
                (
                    "bill_collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bill_comparisons",
                        to="utility_rate.StoredBillCalculation",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "unique_together": {("start", "end_limit", "bill_collection")},
            },
            bases=(django_auto_repr.AutoRepr, models.Model),
        ),
    ]
