# Generated by Django 2.2.7 on 2020-03-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("utility_rate", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="storedbillcalculation",
            name="post_DER_total",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="storedbillcalculation",
            name="pre_DER_total",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
