# Generated by Django 2.2.2 on 2019-07-24 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("utility_rate", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="storedbillcalculation",
            name="rate_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stored_bill_calculations",
                to="utility_rate.RatePlan",
            ),
        )
    ]
