# Generated by Django 2.2.7 on 2020-10-06 22:19

from django.db import migrations, models


def flatten_sector(apps, schema_editor):
    Sector = apps.get_model("reference_model", "Sector")
    RatePlan = apps.get_model("utility_rate", "RatePlan")
    for rp in RatePlan.objects.all():
        if rp.sector.isnumeric():
            sector_id = int(rp.sector)
            sector = Sector.objects.filter(id=sector_id).first()
            if sector is not None:
                rp.sector = sector.name
                rp.save()


class Migration(migrations.Migration):

    dependencies = [
        ("utility_rate", "0002_auto_20200330_2207"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rateplan",
            name="voltage_category",
        ),
        migrations.AlterField(
            model_name="rateplan",
            name="sector",
            field=models.CharField(
                choices=[
                    ("Industrial", "Industrial"),
                    ("Residential", "Residential"),
                    ("Commercial", "Commercial"),
                    ("Agricultural", "Agricultural"),
                    ("Lighting", "Lighting"),
                ],
                max_length=12,
            ),
        ),
        migrations.RunPython(flatten_sector),
    ]
