# Generated by Django 2.2.7 on 2020-10-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("utility_rate", "0003_auto_20201014_2237")]

    operations = [
        migrations.AddField(
            model_name="storedbillcalculation",
            name="stacked",
            field=models.BooleanField(default=False),
        )
    ]
