# Generated by Django 2.2.7 on 2020-10-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_model", "0010_auto_20201014_2237"),
        ("utility_rate", "0004_storedbillcalculation_stacked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storedbillcalculation",
            name="stacked",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name="storedbillcalculation",
            unique_together={("der_simulation", "rate_plan", "stacked")},
        ),
    ]
