# Generated by Django 2.1.4 on 2019-01-23 19:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BuildingType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("floor_area", models.IntegerField()),
                ("number_of_floors", models.IntegerField()),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ReferenceBuilding",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=64)),
                (
                    "state",
                    localflavor.us.models.USStateField(
                        blank=True, max_length=2
                    ),
                ),
                (
                    "TMY3_id",
                    models.IntegerField(
                        db_index=True,
                        validators=[
                            django.core.validators.MinValueValidator(100000),
                            django.core.validators.MaxValueValidator(999999),
                        ],
                    ),
                ),
                ("source_file", models.URLField(max_length=254)),
                (
                    "building_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reference_buildings",
                        to="openei.BuildingType",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
