# Generated by Django 2.1.7 on 2019-03-27 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reference_unit", "0001_initial"),
        ("openei", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="referencebuilding",
            old_name="source_file",
            new_name="source_file_url",
        ),
        migrations.AddField(
            model_name="referencebuilding",
            name="data_unit",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reference_buildings",
                to="reference_unit.DataUnit",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="referencebuilding",
            name="building_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reference_buildings",
                to="reference_unit.BuildingType",
            ),
        ),
        migrations.DeleteModel(name="BuildingType"),
    ]
