# Generated by Django 2.2.2 on 2019-07-10 18:28

import beo_datastore.libs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("reference_model", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="GHGRate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("effective", models.DateField(blank=True, null=True)),
                (
                    "source",
                    models.URLField(blank=True, max_length=128, null=True),
                ),
                (
                    "rate_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ghg_rates",
                        to="reference_model.RateUnit",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "unique_together": {("name", "effective")},
            },
            bases=(models.Model, beo_datastore.libs.models.Frame288FileMixin),
        )
    ]
