# Generated by Django 2.2.7 on 2020-03-04 22:33

import beo_datastore.libs.models
from django.db import migrations, models
import django.db.models.deletion
import django_auto_repr


class Migration(migrations.Migration):

    initial = True

    dependencies = [("reference_model", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="GHGRate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("effective", models.DateField(blank=True, null=True)),
                (
                    "source",
                    models.URLField(blank=True, max_length=128, null=True),
                ),
                (
                    "rate_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ghg_rates",
                        to="reference_model.RateUnit",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "unique_together": {("name", "effective")},
            },
            bases=(
                beo_datastore.libs.models.Frame288FileMixin,
                django_auto_repr.AutoRepr,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="StoredGHGCalculation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pre_DER_total", models.FloatField()),
                ("post_DER_total", models.FloatField()),
                (
                    "der_simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stored_ghg_calculations",
                        to="reference_model.DERSimulation",
                    ),
                ),
                (
                    "ghg_rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stored_ghg_calculations",
                        to="ghg.GHGRate",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "unique_together": {("der_simulation", "ghg_rate")},
            },
            bases=(django_auto_repr.AutoRepr, models.Model),
        ),
    ]
