# Generated by Django 2.2.7 on 2020-10-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ghg", "0002_auto_20200319_1747")]

    operations = [
        migrations.AddField(
            model_name="storedghgcalculation",
            name="stacked",
            field=models.BooleanField(default=False),
        )
    ]
